### ISSUE TITLE
Little bug when trying to use File>PDF Export or File>PNG Export

### ISSUE THREAD

**Issue by ghost** [nejohnson/XSchem#1]
Thanks a lot for this "version" of xschem. This version made my day since it can be compiled as-is on macosx Big Sur :-)
However, there is a little issue that I suspect has to do with having the .sch files in a path with white spaces
(e.g. iCloud)

It doesn't seem to be a problem with the proc in the xschem.tcl (even if a make the proc just puts "hello" the problem 
is still there, but it disappears if I have my .sch in a path without spaces)

Here is the error message I get.

`tcleval(): evaluation of script: convert_to_pdf /tmp/psplot_A7fxwOThUf /Users/claudio/Library/Mobile Documents/com~apple~CloudDocs/ngs406/xSchems/tgate.pdf failed`

Thanks a lot,
Claudio

**Comment by nejohnson** [comment]
Hi,
Yes I believe this issue was fixed on the main branch.  I've beel rather busy of late, but I'll try to sync up this week.
Cheers, Neil

**Comment by ghost** [comment]
Thanks Neil,
Claudio

**Comment by nejohnson** [comment]
Try now.

**Comment by ghost** [comment]
Thanks Neil,
I tested and it works like a charm :-)

Claudio

**Comment by nejohnson** [comment]
Awesome!!!
