### ISSUE TITLE
xschem in command mode 

### ISSUE THREAD

**Issue by AhmedLilah** [nejohnson/XSchem#2]
I'm looking to use xschem in command mode only but there doesn't seem to be a comprehensive doc for the commands .

if there is a doc for how to use command mode for schematic entry among all the other uses please refer to it. otherwise, your help will be very appreciated if you can make such a document.

**Comment by nejohnson** [comment]
Best to check the main xschem project in SourceForge.  This is my own repo that tracks the project as an d when I update it.
